name: macos-gcc-ld

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          cmake . -DCMAKE_C_COMPILER=gcc
          
          cmake --build . --verbose && ./linker_hax
