name: ubuntu-clang-ld

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and run
        run: |
          cmake . -DCMAKE_C_COMPILER=clang
          
          cmake --build . --verbose && ./linker_hax
